all:
  hosts:
    net1:
      ansible_host: 192.168.56.10
    net2:
      ansible_host: 192.168.56.11

  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_become: true
    ansible_become_password: vagrant